name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --ipc=host

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        env:
          MONGODB_URI: "mongodb://localhost:27017"
          user_name: ${{ secrets.user_name }} # Load user_name from GitHub Secrets
          password: ${{ secrets.password }} # Load password from GitHub Secrets
        run: |
          pytest --maxfail=1 --disable-warnings -v
